#!/usr/bin/env bash

set -e

shopt -s dotglob

for dir in */; do
    [[ $dir == ".git/" ]] && continue
    if [[ -f ${dir}.path ]]; then
        dest=$(eval echo $(<${dir}.path))

        find ${dir} -type f -not -name '.path' -exec cp -r {} ${dest} \;
        echo "[+] Files copied from ${dir} to ${dest}"
    else
        echo "[!] Error: .path file not found in ${dir}"
    fi
done
